### ISSUE TITLE
[BUG] Evoweb\SfRegister\Services\Mail::getSubject() must be of the type string, null returned

### ISSUE THREAD

**Issue by linawolf** [evoWeb/sf_register#175] opened 2022-01-10 08:59 UTC
TYPO3: 11.5.4
evoweb/sf-register: 11.0.0

On sending user registration I get the following error:

Return value of Evoweb\SfRegister\Services\Mail::getSubject() must be of the type string, null returned

in /var/www/html/web/typo3conf/ext/sf_register/Classes/Services/Mail.php line 123

**Comment by linawolf** [comment] 2022-01-10 09:02
The method there expects a Evoweb\SfRegister\Domain\Model\FrontendUserInterface which is missing in the Model folder...

**Comment by garbast** [comment] 2022-01-10 13:45
There is a 11.1.0 tag released. And on your comment that the Interface is missing, please have look at https://github.com/evoWeb/sf_register/blob/develop/Classes/Domain/Model/FrontendUserInterface.php

**Comment by haithem-daoud** [comment] 2022-01-10 16:00
Hello, I'm trying to send a notification message to the user after registration using (sf_register extension, TYPO3 v11) but for some reason I'm getting a 503 error message, I've debugged into the issue and it seems that the name of the targeted notification file is not the same (NotifyAdminCreateSave | NotifyAdmincreateSave).
Even if I fix that I got an other problem where the user model is not defined anymore : userNotFound error.
What could be the issue ? Do anybody have any idea about it ?
![image](https://user-images.githubusercontent.com/76599717/148797248-d57f2ef0-2008-4733-943d-9c2384aaf8a5.png)

**Comment by garbast** [comment] 2022-01-11 06:30
The problem in your screenshot is because there is noch subject returen. This is fixed in the dev-develop branch. Please use that branch until a new release.

**Comment by linawolf** [comment] 2022-01-11 07:43
> There is a 11.1.0 tag released. And on your comment that the Interface is missing, please have look at https://github.com/evoWeb/sf_register/blob/develop/Classes/Domain/Model/FrontendUserInterface.php

Yes, I deleted the comment about the missing interface. Seems like something was wrong locally, after I deleted the extension and reinstalled it the extension the interface was there.

**Comment by Apen** [comment] 2022-01-11 08:26
There is a bug who is visible on the screenshot "create" is in lower case, and it should be "subjectNotifyAdminCreateSave".
I think it is a regression introduce in the $controller var in the controller who are declared in lower case.

In "Mail", "sendNotify" methods we should force ucfirst() in `$method = 'NotifyUser' . ucfirst($controller) . $action;`. 
With this, all is good.

But i dont know i there is another side effect of this lower case variable.

**Comment by garbast** [comment] 2022-01-11 08:51
@Apen You are right, the $controller must contain an uppercase name, which was introduced in commit c82405f4. I prevere to fixe it in the class variables because the $this->controller is used in isNofiyAdmin and sendNotifyAdmin and same with the user related functions.

**Closed** 2022-01-11 09:00 UTC
