### ISSUE TITLE
BE: Tabs content elements messed up

### ISSUE THREAD

**Issue by criwe** [evoWeb/sf_register#217] opened 2023-01-13 16:27 UTC
Hi!

I´ve encountered a strange behaviour: after installing sf_register, the tabs when creating content-elements are messed up:

![menu](https://user-images.githubusercontent.com/7531138/212369534-37a14dc4-ebd7-426b-8cf0-2927484d7261.jpg)

After deinstalling sf_register, its sorted like expected.

TYPO3 11
PHP 7.4

Can anyone reproduce the behaviour?!
Best regards,
Christoph

**Comment by garbast** [comment] 2023-01-14 10:21
Can't reproduce. Maybe it has to do with the loading order of the extensions. Please check if it the problem is solved in the develop branch.

**Comment by criwe** [comment] 2023-01-16 13:13
Thanks for the fast reply!
With the development branch the order looks fine :-)

Best regards
Christoph

**Comment by garbast** [comment] 2023-08-23 11:16
Will be part of next release

**Closed by garbast** 2023-08-23 11:16 UTC
